version: '3.1'
services:
  db:
    container_name: postgres
    image: postgres:15.0
    command: "postgres -c config_file=/config/postgresql.conf"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin009"
      POSTGRES_DB: "pgdb"
      PGDATA: "/data"
    volumes:
    - ./pgdata:/data
    - ./config:/config/
    ports:
    - 5432:5432